### ISSUE TITLE
Use of const in strict mode

### ISSUE THREAD

**Issue by JeffreyJamesAttenti** [legraphista/stresser#1]
I just fetched stresser with npm and I get this error when I execute "stresser". I have node v0.12.7 installed on a windows 7 machine.

c:......\AppData\Roaming\npm\node_modules\stresser\index.js:3

`const cluster = require('cluster');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3`

**Comment by hawkrives** [comment]
According to the [`package.json#L12`](https://github.com/legraphista/stresser/blob/master/package.json#L12), this package wants at least Node v4.0.0.

**Comment by JeffreyJamesAttenti** [comment]
Ok thanks.
